name: ci

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main', 'dev']
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install tar y gzip
        run: sudo apt-get install tar gzip -y
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npm run lint
      - name: Run tests
        env:
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME}}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY}}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET}}
        run:
          echo "CLOUDINARY_CLOUD_NAME: $CLOUDINARY_CLOUD_NAME"
          echo "CLOUDINARY_API_KEY: $CLOUDINARY_API_KEY"
          echo "CLOUDINARY_API_SECRET: $CLOUDINARY_API_SECRET"
          npm run test
